### ISSUE TITLE
Sattelite unicode character support

### ISSUE THREAD

**Issue by PeterGhimself** [alexandrevicenzi/emojis#3]
```
$ python -i
Python 3.6.4rc1 (v3.6.4rc1:3398dcb, Dec  5 2017, 19:55:08) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import emojis
>>> emojis.db.get_emoji_by_code('\u2728')
Emoji(aliases=['sparkles'], emoji='\u2728', tags=['shiny'], category='Activities')
>>> emojis.db.get_emoji_by_code('\U0001f916')
Emoji(aliases=['robot'], emoji='\U0001f916', tags=[], category='Smileys & Emotion')
>>> emojis.db.get_emoji_by_code('\U0001f6f0')
>>> emojis.db.get_emoji_by_code('\U0001f680')
Emoji(aliases=['rocket'], emoji='\U0001f680', tags=['ship', 'launch'], category='Travel & Places')
>>> emojis.db.get_emoji_by_code('\U0001F4E1')
Emoji(aliases=['satellite'], emoji='\U0001f4e1', tags=['signal'], category='Objects')
```

The emoji currently labelled `satellite` should be renamed `satellite dish` (or some other suitable name) and the [satellite](http://www.fileformat.info/info/unicode/char/1f6f0/index.htm) emoji with unicode point `\U0001f6f0` should be added to `db.py`.

**Comment by PeterGhimself** [comment]
I have no idea why... but all of a sudden it is working.
I was trying to fix the problem but after a while I reverted the changes back and note this is exactly the same value that I tried before. Could have been some kind of [PEBKAC](https://www.computerhope.com/jargon/p/pebkac.htm) error. I cannot reproduce the issue anymore.

```
>>> import emojis
>>> emojis.db.get_emoji_by_code('\U0001f6f0')
Emoji(aliases=['artificial_satellite'], emoji='\U0001f6f0', tags=['orbit', 'space'], category='Travel & Places')
```

**Comment by alexandrevicenzi** [comment]
If new Emojis are added to [gemoji](https://github.com/github/gemoji) you need to run `make db` to include it in this library.
